"""switch to action-resource model for Permission

Revision ID: 775842e2a565
Revises: 59e85c83bab9
Create Date: 2025-08-07 14:55:49.375754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775842e2a565'
down_revision: Union[str, Sequence[str], None] = '59e85c83bab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('action', sa.String(), nullable=False))
    op.add_column('permissions', sa.Column('resource', sa.String(), nullable=False))
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_column('permissions', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=1)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.drop_column('permissions', 'resource')
    op.drop_column('permissions', 'action')
    # ### end Alembic commands ###
