"""switch to many-to-many user-roles

Revision ID: 8d246e81ee2b
Revises: 808158b1b174
Create Date: 2025-08-07 14:30:24.595655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d246e81ee2b'
down_revision: Union[str, Sequence[str], None] = '808158b1b174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # op.drop_constraint(None, 'users', type_='foreignkey')
    #op.drop_column('users', 'role_id')
    with op.batch_alter_table("users") as batch_op:
     batch_op.drop_column("role_id")


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
